export const BOOK_PAGE_WIDTH = 630;
export const BOOK_PAGE_HEIGHT = 891;

export const SINGLE_PAGE_ASPECT_RATIO = BOOK_PAGE_WIDTH / BOOK_PAGE_HEIGHT;
export const BREAK_ASPECT_RATIO = SINGLE_PAGE_ASPECT_RATIO * 1.5;
