services:
  frontend:
    image: node:lts-jod
    container_name: frontend
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
      - ./shared:/app/shared
      - ./.env:/app/.env
      - /app/frontend/node_modules
    command: sh -c "npm install && npm run dev"
    ports:
      - "${FRONTEND_DEV_PORT}:${FRONTEND_DEV_PORT}"
    depends_on:
      - backend

  backend:
    image: node:lts-jod
    container_name: backend
    hostname: "${BACKEND_HOST}"
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend
      - ./shared:/app/shared
      - ./.env:/app/.env
      - /app/backend/node_modules
    command: sh -c "npm install && npm run dev"
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - postgres
      - rabbitmq
      - chromadb

  nlp:
    image: python:3.12
    container_name: nlp
    working_dir: /app/nlp
    volumes:
      - ./nlp:/app/nlp
      - ./.env:/app/.env
      - /app/nlp/.venv
      - /app/nlp/nltk_data
    command: sh -c "python -m prepare dev && python -u dev.py"
    depends_on:
      - rabbitmq

  postgres:
    image: postgres:15
    container_name: postgres
    hostname: "${POSTGRES_HOST}"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_MAIN_DB}"
      PGPORT: "${POSTGRES_PORT}"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: "${RABBITMQ_HOST}"
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
      - "15672:15672" # management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_NODE_PORT: "${RABBITMQ_PORT}"
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq

  chromadb:
    image: chromadb/chroma:1.0.16.dev77
    container_name: chromadb
    hostname: "${CHROMA_DB_HOST}"
    ports:
      - "${CHROMA_DB_PORT}:${CHROMA_DB_PORT}"
    expose:
      - "${CHROMA_DB_PORT}"
    working_dir: /app/chromadb
    command:
      [
        "run",
        "--path",
        "./chroma_data",
        "--port",
        "${CHROMA_DB_PORT}",
        "--host",
        "chromadb",
      ]
    volumes:
      - ./chroma_data:/app/chromadb/chroma_data
